; ================= Xdebug =================
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.discover_client_host=1
xdebug.log=/tmp/xdebug.log
xdebug.client_port = 9003
xdebug.idekey = "PHPSTORM"

; ================= Opcache =================
opcache.enable = On

; ================= JIT =================
opcache.jit_buffer_size=128M
opcache.jit=1254

; ================= General =================
expose_php = off

; ================= Upload =================
upload_max_filesize = 5M
post_max_size = 12M

; ================= Error reporting =================
display_errors = On
display_startup_errors = On
error_reporting = E_ALL

; ================= Session Redis =================
; Sử dụng Redis thay vì file để lưu session
session.save_handler = redis
session.save_path = "tcp://web-redis:6379"

; Token lưu localStorage, không dùng cookie
session.use_cookies = 1
session.use_only_cookies = 1
session.use_trans_sid = 0

; Thời gian sống session (1 giờ)
session.gc_maxlifetime = 3600
session.cookie_lifetime = 0
